"""initial schema

Revision ID: 88e09699739d
Revises: 
Create Date: 2025-07-17 18:22:17.095662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88e09699739d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_configs', 'machine_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('agent_configs_organization_id_agent_id_key'), 'agent_configs', type_='unique')
    op.drop_index(op.f('idx_agent_configs_org_id'), table_name='agent_configs')
    op.drop_index(op.f('idx_agent_configs_user_id'), table_name='agent_configs')
    op.create_index(op.f('ix_agent_configs_id'), 'agent_configs', ['id'], unique=False)
    op.create_unique_constraint('uq_org_agentid', 'agent_configs', ['organization_id', 'agent_id'])
    op.alter_column('agent_status', 'agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_agent_status_org_agent'), table_name='agent_status')
    op.drop_index(op.f('idx_agent_status_org_id'), table_name='agent_status')
    op.drop_index(op.f('idx_agent_status_user_id'), table_name='agent_status')
    op.create_index(op.f('ix_agent_status_id'), 'agent_status', ['id'], unique=False)
    op.alter_column('app_website_rules', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('app_website_rules', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'uncategorized'::text"))
    op.drop_constraint(op.f('app_website_rules_organization_id_type_pattern_key'), 'app_website_rules', type_='unique')
    op.drop_index(op.f('idx_app_website_rules_org_type_pattern'), table_name='app_website_rules')
    op.create_index(op.f('ix_app_website_rules_id'), 'app_website_rules', ['id'], unique=False)
    op.create_unique_constraint('uq_org_type_pattern', 'app_website_rules', ['organization_id', 'type', 'pattern'])
    op.drop_constraint(op.f('group_viewers_group_id_viewer_id_key'), 'group_viewers', type_='unique')
    op.drop_constraint(op.f('group_viewers_organization_id_group_id_viewer_id_key'), 'group_viewers', type_='unique')
    op.drop_index(op.f('idx_group_viewers_group'), table_name='group_viewers')
    op.drop_index(op.f('idx_group_viewers_org_id'), table_name='group_viewers')
    op.drop_index(op.f('idx_group_viewers_viewer'), table_name='group_viewers')
    op.create_index(op.f('ix_group_viewers_id'), 'group_viewers', ['id'], unique=False)
    op.create_unique_constraint('uq_group_viewer', 'group_viewers', ['group_id', 'viewer_id'])
    op.create_unique_constraint('uq_org_group_viewer', 'group_viewers', ['organization_id', 'group_id', 'viewer_id'])
    op.drop_constraint(op.f('groups_organization_id_name_key'), 'groups', type_='unique')
    op.drop_index(op.f('idx_groups_org_id'), table_name='groups')
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_unique_constraint('uq_org_groupname', 'groups', ['organization_id', 'name'])
    op.alter_column('organizations', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.alter_column('screenshots', 'agent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_screenshots_org_agent'), table_name='screenshots')
    op.drop_index(op.f('idx_screenshots_org_id'), table_name='screenshots')
    op.drop_index(op.f('idx_screenshots_org_user'), table_name='screenshots')
    op.drop_index(op.f('idx_screenshots_user_id'), table_name='screenshots')
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    op.drop_index(op.f('idx_user_groups_group'), table_name='user_groups')
    op.drop_index(op.f('idx_user_groups_org_id'), table_name='user_groups')
    op.drop_index(op.f('idx_user_groups_user'), table_name='user_groups')
    op.drop_constraint(op.f('user_groups_organization_id_user_id_group_id_key'), 'user_groups', type_='unique')
    op.drop_constraint(op.f('user_groups_user_id_group_id_key'), 'user_groups', type_='unique')
    op.create_index(op.f('ix_user_groups_id'), 'user_groups', ['id'], unique=False)
    op.create_unique_constraint('uq_org_user_group', 'user_groups', ['organization_id', 'user_id', 'group_id'])
    op.create_unique_constraint('uq_user_group', 'user_groups', ['user_id', 'group_id'])
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_org_id'), table_name='users')
    op.drop_constraint(op.f('users_organization_id_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint('uq_org_username', 'users', ['organization_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_username', 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_organization_id_username_key'), 'users', ['organization_id', 'username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_org_id'), 'users', ['organization_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_group', 'user_groups', type_='unique')
    op.drop_constraint('uq_org_user_group', 'user_groups', type_='unique')
    op.drop_index(op.f('ix_user_groups_id'), table_name='user_groups')
    op.create_unique_constraint(op.f('user_groups_user_id_group_id_key'), 'user_groups', ['user_id', 'group_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_groups_organization_id_user_id_group_id_key'), 'user_groups', ['organization_id', 'user_id', 'group_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_groups_user'), 'user_groups', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_groups_org_id'), 'user_groups', ['organization_id'], unique=False)
    op.create_index(op.f('idx_user_groups_group'), 'user_groups', ['group_id'], unique=False)
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.create_index(op.f('idx_screenshots_user_id'), 'screenshots', ['user_id'], unique=False)
    op.create_index(op.f('idx_screenshots_org_user'), 'screenshots', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_screenshots_org_id'), 'screenshots', ['organization_id'], unique=False)
    op.create_index(op.f('idx_screenshots_org_agent'), 'screenshots', ['organization_id', 'agent_id'], unique=False)
    op.alter_column('screenshots', 'agent_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.alter_column('organizations', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_org_groupname', 'groups', type_='unique')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.create_index(op.f('idx_groups_org_id'), 'groups', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('groups_organization_id_name_key'), 'groups', ['organization_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_org_group_viewer', 'group_viewers', type_='unique')
    op.drop_constraint('uq_group_viewer', 'group_viewers', type_='unique')
    op.drop_index(op.f('ix_group_viewers_id'), table_name='group_viewers')
    op.create_index(op.f('idx_group_viewers_viewer'), 'group_viewers', ['viewer_id'], unique=False)
    op.create_index(op.f('idx_group_viewers_org_id'), 'group_viewers', ['organization_id'], unique=False)
    op.create_index(op.f('idx_group_viewers_group'), 'group_viewers', ['group_id'], unique=False)
    op.create_unique_constraint(op.f('group_viewers_organization_id_group_id_viewer_id_key'), 'group_viewers', ['organization_id', 'group_id', 'viewer_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('group_viewers_group_id_viewer_id_key'), 'group_viewers', ['group_id', 'viewer_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_org_type_pattern', 'app_website_rules', type_='unique')
    op.drop_index(op.f('ix_app_website_rules_id'), table_name='app_website_rules')
    op.create_index(op.f('idx_app_website_rules_org_type_pattern'), 'app_website_rules', ['organization_id', 'type', 'pattern'], unique=False)
    op.create_unique_constraint(op.f('app_website_rules_organization_id_type_pattern_key'), 'app_website_rules', ['organization_id', 'type', 'pattern'], postgresql_nulls_not_distinct=False)
    op.alter_column('app_website_rules', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'uncategorized'::text"))
    op.alter_column('app_website_rules', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_status_id'), table_name='agent_status')
    op.create_index(op.f('idx_agent_status_user_id'), 'agent_status', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_status_org_id'), 'agent_status', ['organization_id'], unique=False)
    op.create_index(op.f('idx_agent_status_org_agent'), 'agent_status', ['organization_id', 'agent_id'], unique=False)
    op.alter_column('agent_status', 'agent_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_org_agentid', 'agent_configs', type_='unique')
    op.drop_index(op.f('ix_agent_configs_id'), table_name='agent_configs')
    op.create_index(op.f('idx_agent_configs_user_id'), 'agent_configs', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_configs_org_id'), 'agent_configs', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('agent_configs_organization_id_agent_id_key'), 'agent_configs', ['organization_id', 'agent_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent_configs', 'machine_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_configs', 'agent_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
